app_admin:
    resource: "@AppBundle/Resources/config/routing/prod/admin/all.yml"
    prefix:   /admin/

app_user:
    resource: "@AppBundle/Resources/config/routing/prod/user/all.yml"
    prefix:   /user/

app_quiz:
    resource: "@AppBundle/Resources/config/routing/prod/quiz/all.yml"
    prefix:   /quiz/

app_home:
    resource: "@AppBundle/Resources/config/routing/prod/home/all.yml"
    prefix:   /

app_contact_message:
    resource: "@AppBundle/Resources/config/routing/prod/contact_message/all.yml"
    prefix:   /contact_message/

app_feature:
    resource: "@AppBundle/Resources/config/routing/prod/feature/all.yml"
    prefix:   /feature/

app_grade:
    resource: "@AppBundle/Resources/config/routing/prod/grade/all.yml"
    prefix:   /grade/

app_contributor:
    resource: "@AppBundle/Resources/config/routing/prod/contributor/all.yml"
    prefix:   /contributor/

app_question:
    resource: "@AppBundle/Resources/config/routing/prod/question/all.yml"
    prefix:   /question/