services:
    app.business.user:
        class: AppBundle\Service\Business\UserBusiness
        parent: app.util.abstract_container_aware
        public: true

    app.business.request:
        class: AppBundle\Service\Business\RequestBusiness
        parent: app.util.abstract_container_aware
        public: true

    app.business.quiz:
        class: AppBundle\Service\Business\QuizBusiness
        parent: app.util.abstract_container_aware
        public: true

    app.business.question:
        class: AppBundle\Service\Business\QuestionBusiness
        parent: app.util.abstract_container_aware
        public: true

    app.business.quiz_session:
        class: AppBundle\Service\Business\QuizSessionBusiness
        parent: app.util.abstract_container_aware
        public: true

    app.business.answer:
        class: AppBundle\Service\Business\AnswerBusiness
        parent: app.util.abstract_container_aware
        public: true