services:
    app.business.user:
        class: AppBundle\Service\Business\UserBusiness
        parent: app.util.abstract_container_aware
        public: true

    app.business.quiz:
        class: AppBundle\Service\Business\QuizBusiness
        parent: app.util.abstract_container_aware
        public: true