services:
    app.form_type_extension:
        class: AppBundle\Form\Extension\FormTypeExtension
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }