services:
    AppBundle\DataFixtures\ORM\DataUserFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\DataCategoryFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\DataQuizFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\DataGroupFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\DataAnswerFixtures:
        tags: [doctrine.fixture.orm]