services:
    AppBundle\DataFixtures\ORM\DataUserFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\DataCategoryFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\DataQuizFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\DataGroupFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\DataAnswerFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\DataFeatureFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\DataGradeFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\DataContributorFixtures:
        tags: [doctrine.fixture.orm]

    #Courses
    AppBundle\DataFixtures\ORM\Courses\DataASc1Fixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\Courses\DataASc2Fixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\Courses\DataBScFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\Courses\DataMSc1Fixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\Courses\DataMSc2Fixtures:
        tags: [doctrine.fixture.orm]