services:
    app.mailer.abstract_mailer:
        abstract: true
        parent: app.util.abstract_container_aware
        calls:
            - [setTwig, ["@twig"]]
            - [setMailer, ["@swiftmailer.mailer"]]
            - [setRouter, ["@router"]]
            - [setParams, ["%mailer_params%"]]

    app.mailer.user.registration:
        class: AppBundle\Service\Mailer\User\RegistrationMailer
        parent: app.mailer.abstract_mailer

    app.mailer.contact_message.summary:
        class: AppBundle\Service\Mailer\ContactMessage\SummaryMailer
        parent: app.mailer.abstract_mailer