app_admin_user:
    resource: "@AppBundle/Resources/config/routing/prod/admin/user/all.yml"
    prefix:   /user/

app_admin_quiz:
    resource: "@AppBundle/Resources/config/routing/prod/admin/quiz/all.yml"
    prefix:   /quiz/

app_admin_question:
    resource: "@AppBundle/Resources/config/routing/prod/admin/question/all.yml"
    prefix:   /question/

app_admin_category:
    resource: "@AppBundle/Resources/config/routing/prod/admin/category/all.yml"
    prefix:   /category/

app_admin_group:
    resource: "@AppBundle/Resources/config/routing/prod/admin/group/all.yml"
    prefix:   /group/

app_admin_chapter:
    resource: "@AppBundle/Resources/config/routing/prod/admin/chapter/all.yml"
    prefix: /chapter/

app_admin_course:
    resource: "@AppBundle/Resources/config/routing/prod/admin/course/all.yml"
    prefix: /course/