# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_USER:  IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_USER_SUBSCRIBER: ROLE_USER
        ROLE_ADMIN: ROLE_USER_SUBSCRIBER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        user_provider:
            entity:
                class: AppBundle:User
                property: idBooster
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            anonymous: ~
            pattern:    ^/
            form_login:
                provider: user_provider
                login_path: app_user_authentication_signing_sign
                check_path: app_user_authentication_signing_check
                default_target_path: app_home_home_index
            logout:
                path:   app_user_authentication_signing_logout
                target: app_home_home_index
            http_basic: ~
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
                path:     /
            user_checker: AppBundle\Service\Security\User\Authentication\Login\LoginChecker

    access_control:
      - { path: ^/user/authentication/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/quiz/, roles: ROLE_USER }
      - { path: ^/grade/, roles: ROLE_USER }
      - { path: ^/admin/, roles: ROLE_ADMIN }
      - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }