app_admin_question_listing:
    resource: "@AppBundle/Resources/config/routing/prod/admin/question/listing.yml"
    prefix:   /listing/

app_admin_question_edition:
    resource: "@AppBundle/Resources/config/routing/prod/admin/question/edition.yml"
    prefix:   /edition/

app_admin_question_creation:
    resource: "@AppBundle/Resources/config/routing/prod/admin/question/creation.yml"
    prefix:   /creation/

app_admin_question_removing:
    resource: "@AppBundle/Resources/config/routing/prod/admin/question/removing.yml"
    prefix:   /removing/

app_admin_question_showing:
    resource: "@AppBundle/Resources/config/routing/prod/admin/question/showing.yml"
    prefix:   /showing/