app_admin_question_creation_create:
    path: /create
    defaults: { _controller: 'AppBundle:Admin/Question/Creation:create' }

app_admin_question_creation_add:
    path: /add/{id}
    defaults: { _controller: 'AppBundle:Admin/Question/Creation:add' }
    requirements:
        id: \d+