app_quiz_list_completed:
    path: /completed
    defaults: { _controller: 'AppBundle:Quiz/Listing:completed' }

app_quiz_list_in_progress:
    path: /in_progress
    defaults: { _controller: 'AppBundle:Quiz/Listing:inProgress' }

app_quiz_list_new:
    path: /new
    defaults: { _controller: 'AppBundle:Quiz/Listing:new' }

app_quiz_listing_list:
    path: /list
    defaults: { _controller: 'AppBundle:Quiz/Listing:listQuiz' }

app_quiz_listing_user:
    path: /user
    defaults: { _controller: 'AppBundle:Quiz\Listing:listUserQuiz' }