AppBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
            nullable: true
    oneToMany:
        quizzes:
            targetEntity: AppBundle\Entity\Quiz
            mappedBy: category
            cascade: [ persist, remove ]
    manyToMany:
        groups:
            targetEntity: AppBundle\Entity\UserGroup
            inversedBy: categories
            joinTable:
                name: categories_groups
                joinColumns:
                    category_id:
                        referencedColumnName: id
                        nullable: false
                        unique: false
                inverseJoinColumns:
                    group_id:
                        referenceColumnName: id
            cascade:
                - all
    lifecycleCallbacks: {  }