AppBundle\Entity\Chapter:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ChapterRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        text:
            type: string
            length: 255

    manyToOne:
        course:
            targetEntity: AppBundle\Entity\Course
            inversedBy: chapters
            cascade: [ persist ]
            joinColumn:
                name: chapter_id
                referencedColumnName: id
                nullable: false
        contributions:
            targetEntity: AppBundle\Entity\Contribution
            inversedBy: icontribution
            cascade: [ persist ]
            joinColumn:
                name: contribution_id
                referencedColumnName: id
                nullable: true

    lifecycleCallbacks: {  }
