AppBundle\Entity\Chapter:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ChapterRepository
    fields:
        title:
            type: string
            length: 255
        text:
            type: string
            length: 80000
    manyToOne:
        course:
            targetEntity: AppBundle\Entity\Course
            inversedBy: chapters
            cascade: [ persist ]
            joinColumn:
                name: chapter_id
                referencedColumnName: id
                nullable: false

    lifecycleCallbacks: {  }
