AppBundle\Entity\Contribution:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ContributionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            cascade: [ persist ]
            inversedBy: user
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
    oneToOne:
        itemContribution:
            targetEntity: AppBundle\Entity\ItemContribution
            cascade: [ persist, remove ]
            joinColumn:
                name: item_contribution_id
                referencedColumnName: id
    lifecycleCallbacks: {  }