AppBundle\Entity\ContactMessage:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ContactMessageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        message:
            type: string
            length: 2000
        email:
            type: string
            length: 255
    lifecycleCallbacks: {  }