AppBundle\Entity\Course:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CourseRepository
    fields:
        title:
            type: string
            length: 255

        description:
            type: string
            length: 255
            nullable: true

    oneToMany:
        chapters:
            targetEntity: AppBundle\Entity\Chapter
            mappedBy: course
            cascade: [ persist, remove ]
        quizzes:
            targetEntity: AppBundle\Entity\Quiz
            mappedBy: course
            cascade: [ persist, remove ]
        subjects:
            targetEntity: AppBundle\Entity\Subject
            mappedBy: course
            cascade: [ persist, remove ]
    manyToOne:
        grade:
            targetEntity: AppBundle\Entity\Grade
            inversedBy: courses
            cascade: [ persist ]
            joinColumn:
                name: grade_id
                referencedColumnName: id
                nullable: true
    lifecycleCallbacks: {  }