AppBundle\Entity\Grade:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GradeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 2000
            nullable: true
        imagePath:
            type: string
            length: 255
    lifecycleCallbacks: {  }
