AppBundle\Entity\Question:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\QuestionRepository
    fields:
        title:
            type: string
            length: 255
            nullable: true
        text:
            type: text
            nullable: true
        responses:
            type: array
        solution:
            type: array
    manyToOne:
        quiz:
            targetEntity: AppBundle\Entity\Quiz
            inversedBy: questions
            cascade: [ persist ]
            joinColumn:
                name: quiz_id
                referencedColumnName: id
                nullable: true
                onDelete: CASCADE
    oneToMany:
        answers:
           targetEntity: AppBundle\Entity\Answer
           mappedBy: question
           cascade: [ persist, remove ]
    lifecycleCallbacks: {  }
