AppBundle\Entity\Quiz:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\QuizRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            nullable: true
        description:
            type: text
            nullable: true
        marks:
            type: array
        resettable:
            type: boolean
        validate:
            type: boolean
        submitted:
            type: boolean
        imagePath:
            type: string
            length: 255
        startingDate:
            type: datetime
            nullable: true
        endingDate:
            type: datetime
            nullable: true
        validationDate:
            type: datetime
            nullable: true
        lastUpdate:
            type: datetime
    oneToMany:
        questions:
            targetEntity: AppBundle\Entity\Question
            mappedBy: quiz
            cascade: [ persist, remove ]
    manyToOne:
        category:
            targetEntity: AppBundle\Entity\Category
            inversedBy: quizzes
            cascade: [ persist ]
            joinColumn:
                name: category_id
                referencedColumnName: id
                nullable: true
        contributions:
            targetEntity: AppBundle\Entity\Contribution
            inversedBy: icontributions
            cascade: [ persist ]
            joinColumn:
                name: contribution_id
                referencedColumnName: id
                nullable: true

    lifecycleCallbacks: {  }
