AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idBooster:
            type: integer
            length: 255
            unique: true
        firstName:
            type: string
            length: 255
            nullable: true
        lastName:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            unique: true
        roles:
            type: array
        password:
            type: string
            length: 4096
        salt:
            type: string
            length: 255
        enabled:
            type: boolean
        token:
            type: string
            length: 255
        forgotPasswordToken:
            type: string
            length: 255
            nullable: true
    manyToMany:
        groups:
            targetEntity: AppBundle\Entity\UserGroup
            inversedBy: users
            joinTable:
                name: users_groups
                joinColumns:
                    user_id:
                        referencedColumnName: id
                        nullable: false
                        unique: false
                inverseJoinColumns:
                    group_id:
                        referenceColumnName: id
            cascade:
                - all
    oneToMany:
        answers:
            targetEntity: AppBundle\Entity\Answer
            mappedBy: user
        contributions:
            targetEntity: AppBundle\Entity\Contribution
            mappedBy: user

    lifecycleCallbacks: {  }
