AppBundle\Entity\UserGroup:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserGroupRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true
    manyToMany:
        users:
            targetEntity: User
            mappedBy: groups
        categories:
            targetEntity: Category
            mappedBy: groups
    lifecycleCallbacks: {  }
