app_admin_user_edition_edit:
    path: /edit/{id}
    defaults: { _controller: 'AppBundle:Admin/User/Edition:edit' }
    requirements:
        id: \d+

app_admin_user_edition_group:
    path: /group/{id}
    defaults: { _controller: 'AppBundle:Admin/User/Edition:group' }
    requirements:
        id: \d+