app_admin_category_edition_edit:
    path: /edit/{id}
    defaults: { _controller: 'AppBundle:Admin/Category/Edition:edit' }
    requirements:
        id: \d+

app_admin_category_edition_group:
    path: /group/{id}
    defaults: { _controller: 'AppBundle:Admin/Category/Edition:group' }
    requirements:
        id: \d+