app_user_authentication_registration:
    resource: "@AppBundle/Resources/config/routing/prod/user/authentication/registration.yml"
    prefix:   /registration/

app_user_authentication_login:
    resource: "@AppBundle/Resources/config/routing/prod/user/authentication/login.yml"
    prefix:   /login/

app_user_authentication_logout:
    resource: "@AppBundle/Resources/config/routing/prod/user/authentication/logout.yml"
    prefix:   /logout/

app_user_authentication_enabling:
    resource: "@AppBundle/Resources/config/routing/prod/user/authentication/enabling.yml"
    prefix:   /enabling/

app_user_authentication_signing:
    resource: "@AppBundle/Resources/config/routing/prod/user/authentication/signing.yml"
    prefix:   /signing/

app_user_authentication_forgot_password:
    resource: "@AppBundle/Resources/config/routing/prod/user/authentication/forgot_password.yml"
    prefix:   /forgot-password/