app_user_authentication_forgot_password_request_new_password:
    path:   /request-new-password/
    defaults: { _controller: 'AppBundle:User\Authentication\ForgetPassword:requestNewPassword' }


app_user_authentication_forgot_password_change_password:
    path:   /change-password/{id}/{token}
    defaults: { _controller: 'AppBundle:User\Authentication\ForgetPassword:changePassword'}
    requirements:
        id: '\d+'